// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsXFBZLdvw4yXQgCIiBY5KWY4aHICki6E',
    appId: '1:812458932745:android:59cee295223f1a584916d8',
    messagingSenderId: '812458932745',
    projectId: 'fcm-share-delivery',
    storageBucket: 'fcm-share-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQ9dca_n79MWeXM-7qr3taR_DluBBLmU',
    appId: '1:812458932745:ios:6b4ce7038a7a03934916d8',
    messagingSenderId: '812458932745',
    projectId: 'fcm-share-delivery',
    storageBucket: 'fcm-share-delivery.appspot.com',
    iosClientId: '812458932745-e198crt0vv20vtdnljtdnb7cm9ll1mdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRQ9dca_n79MWeXM-7qr3taR_DluBBLmU',
    appId: '1:812458932745:ios:6b4ce7038a7a03934916d8',
    messagingSenderId: '812458932745',
    projectId: 'fcm-share-delivery',
    storageBucket: 'fcm-share-delivery.appspot.com',
    iosClientId: '812458932745-e198crt0vv20vtdnljtdnb7cm9ll1mdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareDelivery',
  );
}
